### PR TITLE
Getter for name of CollisionDetectorAllocator

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Here is the PR to change the interface for the CollisionDetectorAllocator objects to have a simple getter method for the name.  Please test this to see if it works for you.

### CODE REVIEW

**Comment by wolfv** [comment]
closing and re-opening to trigger the new CI as well! I had to add some `on: ...` conditions. Thanks for the PR :tada:

**Review by v4hn — COMMENTED** [review]
Please add a short MIGRATIONS.md entry for this change.

Please keep a clean history for the Windows-Support PR though. I don't think we need to keep the EXPORT/IMPORT helper commits at all.

**Comment by tylerjw** [comment]
> Please add a short MIGRATIONS.md entry for this change.

@v4hn Done, what do you think of what I wrote in the migration notes for this?  Do we pre-pend to the lists there or do we add the newest changes to the end of the list?

> Please keep a clean history for the Windows-Support PR though. I don't think we need to keep the EXPORT/IMPORT helper commits at all.

@wolfv do you understand how to do this?  If not I can walk you through it or do it for you.  The steps I would do to do this would be to edit the commits where those lines come with an interactive rebase and cherry pick this commit at the end (you'll probably need to do a merge conflict when you do that).

**Comment by v4hn** [comment]
> Done, what do you think of what I wrote in the migration notes for this?

:+1:

> Do we pre-pend to the lists there or do we add the newest changes to the end of the list?

I would append at the bottom, but I'm not sure we were consistent in the past.
In the future we want to prepend for sure because there will be no regular ROS distributions for ROS anymore.

**Pull request merged**
